def allCultures():
    return [
        {"id": 1, "name": "Caqui", "period": "junho a julho / dezembro - janeiro"},
        {"id": 2, "name": "Cenoura", "period": "ano todo"},
        {"id": 3, "name": "Banana", "period": "ano todo"},
        {"id": 4, "name": "Soja", "period": "outubro"},
        {"id": 5, "name": "Milho", "period": "outubro"},
        {"id": 6, "name": "Tomate", "period": "agosto"},
        {"id": 7, "name": "Uva", "period": "julho"},
        {"id": 8, "name": "Laranja", "period": "ano todo"},
        {"id": 9, "name": "Figo", "period": "ano todo"},
        {"id": 10, "name": "Cana de açúcar", "period": "outubro"},
        {"id": 11, "name": "Beterraba", "period": "fevereiro - junho"},
        {"id": 12, "name": "Repolho", "period": "ano todo"},
        {"id": 13, "name": "Café", "period": "outubro"},
        {"id": 14, "name": "Manga", "period": "outubro - março"},
        {"id": 15, "name": "Pêssego", "period": "julho"}, 
        {"id": 16, "name": "Limão", "period": "março"}, 
        {"id": 17, "name": "Feijão", "period": "outubro"}, 
        {"id": 18, "name": "Hortelã", "period": "ano todo"}, 
        {"id": 19, "name": "Alface", "period": "março"}, 
        {"id": 20, "name": "Amendoim", "period": "setembro - novembro"}, 
    ]

def allCities():
    return [
        {"id": 1, "slug": "jacarei", "name": "Jacareí", "state": "SP", "code": 3524402},
        {"id": 2, "slug": "sao-paulo", "name": "São Paulo", "state": "SP", "code": 3550308}, 
        {"id": 3, "slug": "sao-vicente", "name": "São Vicente", "state": "SP", "code": 3551009}, 
        {"id": 4, "slug": "santos", "name": "Santos", "state": "SP", "code": 3548500}, 
        {"id": 5, "slug": "miracatu", "name": "Miracatu", "state": "SP", "code": 3529906},
        {"id": 6, "slug": "registro", "name": "Registro", "state": "SP", "code": 3542602},
        {"id": 7, "slug": "itapeva", "name": "Itapeva", "state": "SP", "code": 3522406},
        {"id": 8, "slug": "apiai", "name": "Apiaí", "state": "SP", "code": 3502705},
        {"id": 9, "slug": "itarare", "name": "Itararé", "state": "SP", "code": 3523206},
        {"id": 10, "slug": "itapetininga", "name": "Itapetininga", "state": "SP", "code": 3522307},
        {"id": 11, "slug": "campinas", "name": "Campinas", "state": "SP", "code": 3509502},
        {"id": 12, "slug": "jundiai", "name": "Jundiaí", "state": "SP", "code": 3525904},
        {"id": 13, "slug": "sumare", "name": "Sumaré", "state": "SP", "code": 3552403},
        {"id": 14, "slug": "mogi-mirim", "name": "Mogi Mirim", "state": "SP", "code": 3530805},
        {"id": 15, "slug": "capivari", "name": "Capivari", "state": "SP", "code": 3510401},
        {"id": 16, "slug": "itu", "name": "Itu", "state": "SP", "code": 3523909},
        {"id": 17, "slug": "sao-roque", "name": "São Roque", "state": "SP", "code": 3550605},
        {"id": 18, "slug": "votorantim", "name": "Votorantim", "state": "SP", "code": 3557006},
        {"id": 19, "slug": "sorocaba", "name": "Sorocaba", "state": "SP", "code": 3552205},
        {"id": 20, "slug": "botucatu", "name": "Botucatu", "state": "SP", "code": 3507506},
        {"id": 21, "slug": "piracicaba", "name": "Piracicaba", "state": "SP", "code": 3538709},
        {"id": 22, "slug": "limeira", "name": "Limeira", "state": "SP", "code": 3526902},
        {"id": 23, "slug": "pirassununga", "name": "Pirassununga", "state": "SP", "code": 3539301},
        {"id": 24, "slug": "jaú", "name": "Jaú", "state": "SP", "code": 3525300},
        {"id": 25, "slug": "araraquara", "name": "Araraquara", "state": "SP", "code": 3503208},
        {"id": 26, "slug": "sao-carlos", "name": "São Carlos", "state": "SP", "code": 3548906},
        {"id": 27, "slug": "bauru", "name": "Bauru", "state": "SP", "code": 3506003},
        {"id": 28, "slug": "ourinhos", "name": "Ourinhos", "state": "SP", "code": 3534708},
        {"id": 29, "slug": "avaré", "name": "Avaré", "state": "SP", "code": 3504503},
        {"id": 30, "slug": "piraju", "name": "Piraju", "state": "SP", "code": 3538808},
        {"id": 31, "slug": "marília", "name": "Marília", "state": "SP", "code": 3529005},
        {"id": 32, "slug": "assis", "name": "Assis", "state": "SP", "code": 3504008},
        {"id": 33, "slug": "lins", "name": "Lins", "state": "SP", "code": 3527108},
        {"id": 34, "slug": "franca", "name": "Franca", "state": "SP", "code": 3516200},
        {"id": 35, "slug": "ribeirao-preto", "name": "Ribeirão Preto", "state": "SP", "code": 3543402},
        {"id": 36, "slug": "sao-joaquim-da-barra", "name": "São Joaquim da Barra", "state": "SP", "code": 3549409},
        {"id": 37, "slug": "sao-joao-da-boa-vista", "name": "São João da Boa Vista", "state": "SP", "code": 3549102},
        {"id": 38, "slug": "barretos", "name": "Barretos", "state": "SP", "code": 3505500},
        {"id": 39, "slug": "sertãozinho", "name": "Sertãozinho", "state": "SP", "code": 3551702},
        {"id": 40, "slug": "jaboticabal", "name": "Jaboticabal", "state": "SP", "code": 3524303},
        {"id": 41, "slug": "taquaritinga", "name": "Taquaritinga", "state": "SP", "code": 3553708},
        {"id": 42, "slug": "catanduva", "name": "Catanduva", "state": "SP", "code": 3511102},
        {"id": 43, "slug": "sao-jose-do-rio-preto", "name": "São José do Rio Preto", "state": "SP", "code": 3549805},
        {"id": 44, "slug": "jose-bonifacio", "name": "José Bonifácio", "state": "SP", "code": 3525706},
        {"id": 45, "slug": "votuporanga", "name": "Votuporanga", "state": "SP", "code": 3557105},
        {"id": 46, "slug": "fernandópolis", "name": "Fernandópolis", "state": "SP", "code": 3515509},
        {"id": 47, "slug": "jales", "name": "Jales", "state": "SP", "code": 3524808},
        {"id": 48, "slug": "andradina", "name": "Andradina", "state": "SP", "code": 3502101},
        {"id": 49, "slug": "araçatuba", "name": "Araçatuba", "state": "SP", "code": 3502804},
        {"id": 50, "slug": "birigui", "name": "Birigui", "state": "SP", "code": 3506508},
        {"id": 51, "slug": "penápolis", "name": "Penápolis", "state": "SP", "code": 3537305},
        {"id": 52, "slug": "presidente-prudente", "name": "Presidente Prudente", "state": "SP", "code": 3541406},
        {"id": 53, "slug": "adamantina", "name": "Adamantina", "state": "SP", "code": 3500105},
        {"id": 54, "slug": "santo-anastacio", "name": "Santo Anastácio", "state": "SP", "code": 3547700},
        {"id": 55, "slug": "mirante-do-paranapanema", "name": "Mirante do Paranapanema", "state": "SP", "code": 3530201},
        {"id": 56, "slug": "branca-paulista", "name": "Bragança Paulista", "state": "SP", "code": 3507605},
    ]

def relationCitiesCultures():
    return [
        {"id": 1, "city_id": 1, "culture_id": 1, "period": "junho a julho / dezembro - janeiro"},
        {"id": 2, "city_id": 1, "culture_id": 2, "period": "ano todo"},
        {"id": 3, "city_id": 2, "culture_id": 3, "period": "ano todo"},
        {"id": 4, "city_id": 3, "culture_id": 3, "period": "ano todo"},
        {"id": 5, "city_id": 4, "culture_id": 3, "period": "ano todo"},
        {"id": 6, "city_id": 5, "culture_id": 3, "period": "ano todo"},
        {"id": 7, "city_id": 6, "culture_id": 3, "period": "ano todo"},
        {"id": 8, "city_id": 7, "culture_id": 4, "period": "outubro"},
        {"id": 9, "city_id": 8, "culture_id": 4, "period": "outubro"},
        {"id": 10, "city_id": 9, "culture_id": 4, "period": "outubro"},
        {"id": 11, "city_id": 28, "culture_id": 4, "period": "outubro"},
        {"id": 12, "city_id": 29, "culture_id": 4, "period": "outubro"},
        {"id": 13, "city_id": 30, "culture_id": 4, "period": "outubro"},
        {"id": 14, "city_id": 32, "culture_id": 4, "period": "outubro"},
        {"id": 15, "city_id": 38, "culture_id": 4, "period": "outubro"},
        {"id": 16, "city_id": 52, "culture_id": 4, "period": "outubro"},
        {"id": 17, "city_id": 7, "culture_id": 5, "period": "outubro"},
        {"id": 18, "city_id": 8, "culture_id": 5, "period": "outubro"},
        {"id": 19, "city_id": 9, "culture_id": 5, "period": "outubro"},
        {"id": 20, "city_id": 32, "culture_id": 5, "period": "outubro"},
        {"id": 21, "city_id": 39, "culture_id": 5, "period": "outubro"},
        {"id": 22, "city_id": 40, "culture_id": 5, "period": "outubro"},
        {"id": 23, "city_id": 41, "culture_id": 5, "period": "outubro"},
        {"id": 24, "city_id": 42, "culture_id": 5, "period": "outubro"},
        {"id": 25, "city_id": 43, "culture_id": 5, "period": "outubro"},
        {"id": 26, "city_id": 47, "culture_id": 5, "period": "outubro"},
        {"id": 27, "city_id": 7, "culture_id": 6, "period": "agosto"},
        {"id": 28, "city_id": 8, "culture_id": 6, "period": "agosto"},
        {"id": 29, "city_id": 9, "culture_id": 6, "period": "agosto"},
        {"id": 30, "city_id": 11, "culture_id": 7, "period": "julho"},
        {"id": 31, "city_id": 12, "culture_id": 7, "period": "julho"},
        {"id": 32, "city_id": 13, "culture_id": 7, "period": "julho"},
        {"id": 33, "city_id": 15, "culture_id": 7, "period": "julho"},
        {"id": 34, "city_id": 16, "culture_id": 7, "period": "julho"},
        {"id": 35, "city_id": 17, "culture_id": 7, "period": "julho"},
        {"id": 36, "city_id": 18, "culture_id": 7, "period": "julho"},
        {"id": 37, "city_id": 19, "culture_id": 7, "period": "julho"},
        {"id": 38, "city_id": 20, "culture_id": 7, "period": "julho"},
        {"id": 39, "city_id": 44, "culture_id": 7, "period": "julho"},
        {"id": 40, "city_id": 45, "culture_id": 7, "period": "julho"},
        {"id": 41, "city_id": 10, "culture_id": 8, "period": "julho"},
        {"id": 42, "city_id": 14, "culture_id": 8, "period": "julho"},
        {"id": 43, "city_id": 20, "culture_id": 8, "period": "julho"},
        {"id": 44, "city_id": 27, "culture_id": 8, "period": "julho"},
        {"id": 45, "city_id": 28, "culture_id": 8, "period": "julho"},
        {"id": 46, "city_id": 29, "culture_id": 8, "period": "julho"},
        {"id": 47, "city_id": 30, "culture_id": 8, "period": "julho"},
        {"id": 48, "city_id": 37, "culture_id": 8, "period": "julho"},
        {"id": 49, "city_id": 38, "culture_id": 8, "period": "julho"},
        {"id": 50, "city_id": 46, "culture_id": 8, "period": "julho"},
        {"id": 51, "city_id": 11, "culture_id": 9, "period": "ano todo"},
        {"id": 52, "city_id": 12, "culture_id": 9, "period": "ano todo"},
        {"id": 53, "city_id": 13, "culture_id": 9, "period": "ano todo"},
        {"id": 54, "city_id": 14, "culture_id": 10, "period": "outubro"},
        {"id": 55, "city_id": 20, "culture_id": 10, "period": "outubro"},
        {"id": 56, "city_id": 21, "culture_id": 10, "period": "outubro"},
        {"id": 57, "city_id": 22, "culture_id": 10, "period": "outubro"},
        {"id": 58, "city_id": 23, "culture_id": 10, "period": "outubro"},
        {"id": 59, "city_id": 24, "culture_id": 10, "period": "outubro"},
        {"id": 60, "city_id": 25, "culture_id": 10, "period": "outubro"},
        {"id": 61, "city_id": 26, "culture_id": 10, "period": "outubro"},
        {"id": 62, "city_id": 27, "culture_id": 10, "period": "outubro"},
        {"id": 63, "city_id": 28, "culture_id": 10, "period": "outubro"},
        {"id": 64, "city_id": 29, "culture_id": 10, "period": "outubro"},
        {"id": 65, "city_id": 30, "culture_id": 10, "period": "outubro"},
        {"id": 66, "city_id": 31, "culture_id": 10, "period": "outubro"},
        {"id": 67, "city_id": 32, "culture_id": 10, "period": "outubro"},
        {"id": 68, "city_id": 33, "culture_id": 10, "period": "outubro"},
        {"id": 69, "city_id": 34, "culture_id": 10, "period": "outubro"},
        {"id": 70, "city_id": 35, "culture_id": 10, "period": "outubro"},
        {"id": 71, "city_id": 36, "culture_id": 10, "period": "outubro"},
        {"id": 72, "city_id": 37, "culture_id": 10, "period": "outubro"},
        {"id": 73, "city_id": 38, "culture_id": 10, "period": "outubro"},
        {"id": 74, "city_id": 39, "culture_id": 10, "period": "outubro"},
        {"id": 75, "city_id": 40, "culture_id": 10, "period": "outubro"},
        {"id": 76, "city_id": 41, "culture_id": 10, "period": "outubro"},
        {"id": 77, "city_id": 42, "culture_id": 10, "period": "outubro"},
        {"id": 78, "city_id": 43, "culture_id": 10, "period": "outubro"},
        {"id": 79, "city_id": 44, "culture_id": 10, "period": "outubro"},
        {"id": 80, "city_id": 45, "culture_id": 10, "period": "outubro"},
        {"id": 81, "city_id": 46, "culture_id": 10, "period": "outubro"},
        {"id": 82, "city_id": 47, "culture_id": 10, "period": "outubro"},
        {"id": 83, "city_id": 48, "culture_id": 10, "period": "outubro"},
        {"id": 84, "city_id": 49, "culture_id": 10, "period": "outubro"},
        {"id": 85, "city_id": 50, "culture_id": 10, "period": "outubro"},
        {"id": 86, "city_id": 51, "culture_id": 10, "period": "outubro"},
        {"id": 87, "city_id": 52, "culture_id": 10, "period": "outubro"},
        {"id": 88, "city_id": 53, "culture_id": 10, "period": "outubro"},
        {"id": 89, "city_id": 54, "culture_id": 10, "period": "outubro"},
        {"id": 90, "city_id": 55, "culture_id": 10, "period": "outubro"},
        {"id": 91, "city_id": 15, "culture_id": 11, "period": "fevereiro - junho"},
        {"id": 92, "city_id": 16, "culture_id": 11, "period": "fevereiro - junho"},
        {"id": 93, "city_id": 17, "culture_id": 11, "period": "fevereiro - junho"},
        {"id": 94, "city_id": 18, "culture_id": 11, "period": "fevereiro - junho"},
        {"id": 95, "city_id": 19, "culture_id": 11, "period": "fevereiro - junho"},
        {"id": 96, "city_id": 15, "culture_id": 12, "period": "ano todo"},
        {"id": 97, "city_id": 16, "culture_id": 12, "period": "ano todo"},
        {"id": 98, "city_id": 17, "culture_id": 12, "period": "ano todo"},
        {"id": 99, "city_id": 18, "culture_id": 12, "period": "ano todo"},
        {"id": 100, "city_id": 19, "culture_id": 12, "period": "ano todo"},
        {"id": 101, "city_id": 31, "culture_id": 13, "period": "outubro"},
        {"id": 102, "city_id": 34, "culture_id": 13, "period": "outubro"},
        {"id": 103, "city_id": 37, "culture_id": 13, "period": "outubro"},
        {"id": 104, "city_id": 39, "culture_id": 14, "period": "outubro - março"},
        {"id": 105, "city_id": 40, "culture_id": 14, "period": "outubro - março"},
        {"id": 106, "city_id": 41, "culture_id": 14, "period": "outubro - março"},
        {"id": 107, "city_id": 42, "culture_id": 14, "period": "outubro - março"},
        {"id": 107, "city_id": 7, "culture_id": 15, "period": "julho"},
        {"id": 107, "city_id": 11, "culture_id": 15, "period": "julho"},
        {"id": 107, "city_id": 56, "culture_id": 15, "period": "julho"},
        {"id": 107, "city_id": 42, "culture_id": 16, "period": "março"},
        {"id": 107, "city_id": 47, "culture_id": 16, "period": "março"},
        {"id": 107, "city_id": 38, "culture_id": 16, "period": "março"},
        {"id": 107, "city_id": 14, "culture_id": 16, "period": "março"},
        {"id": 107, "city_id": 40, "culture_id": 16, "period": "março"},
        {"id": 107, "city_id": 7, "culture_id": 17, "period": "outubro"},
        {"id": 107, "city_id": 38, "culture_id": 17, "period": "outubro"},
        {"id": 107, "city_id": 9, "culture_id": 17, "period": "outubro"},
        {"id": 107, "city_id": 2, "culture_id": 18, "period": "ano todo"},
        {"id": 107, "city_id": 19, "culture_id": 18, "period": "ano todo"},
        {"id": 107, "city_id": 11, "culture_id": 18, "period": "ano todo"},
        {"id": 107, "city_id": 35, "culture_id": 20, "period": "setembro - novembro"},
        {"id": 107, "city_id": 40, "culture_id": 20, "period": "setembro - novembro"},
    ]