def cultures():
    return [
        {"id": 1, "name": "Caqui", "period": "jun - jul / dez - jan"},
        {"id": 2, "name": "Cenoura", "period": "ano todo"},
        {"id": 3, "name": "Banana", "period": "ano todo"},
        {"id": 4, "name": "Soja", "period": "out"},
        {"id": 5, "name": "Milho", "period": "out"},
        {"id": 6, "name": "Tomate", "period": "ago"},
        {"id": 7, "name": "Uva", "period": "jul"},
        {"id": 8, "name": "Laranja", "period": "ano todo"},
        {"id": 9, "name": "Figo", "period": "ano todo"},
        {"id": 10, "name": "Cana de açúcar", "period": "out"},
        {"id": 11, "name": "Beterraba", "period": "fev - jun"},
        {"id": 12, "name": "Repolho", "period": "ano todo"},
        {"id": 13, "name": "Café", "period": "out"},
        {"id": 14, "name": "Manga", "period": "out - mar"},
        {"id": 15, "name": "Pêssego", "period": "jul"}, 
        {"id": 16, "name": "Limão", "period": "mar"}, 
        {"id": 17, "name": "Feijão", "period": "out"}, 
        {"id": 18, "name": "Hortelã", "period": "ano todo"}, 
        {"id": 19, "name": "Alface", "period": "mar"}, 
        {"id": 20, "name": "Amendoim", "period": "set - nov"}, 
    ]

def cities():
    return [
        {"id": 1, "name": "Jacareí", "state": "SP"},
        {"id": 2, "name": "São Paulo", "state": "SP"}, 
        {"id": 3, "name": "São Vicente", "state": "SP"}, 
        {"id": 4, "name": "Santos", "state": "SP"}, 
        {"id": 5, "name": "Miracatu", "state": "SP"},
        {"id": 6, "name": "Registro", "state": "SP"},
        {"id": 7, "name": "Itapeva", "state": "SP"},
        {"id": 8, "name": "Apiai", "state": "SP"},
        {"id": 9, "name": "Itararé", "state": "SP"},
        {"id": 10, "name": "Itapetininga", "state": "SP"},
        {"id": 11, "name": "Campinas", "state": "SP"},
        {"id": 12, "name": "Jundiaí", "state": "SP"},
        {"id": 13, "name": "Sumaré", "state": "SP"},
        {"id": 14, "name": "Mogi Mirim", "state": "SP"},
        {"id": 15, "name": "Capivari", "state": "SP"},
        {"id": 16, "name": "Itu", "state": "SP"},
        {"id": 17, "name": "São Roque", "state": "SP"},
        {"id": 18, "name": "Votorantim", "state": "SP"},
        {"id": 19, "name": "Sorocaba", "state": "SP"},
        {"id": 20, "name": "Botucatu", "state": "SP"},
        {"id": 21, "name": "Piracicaba", "state": "SP"},
        {"id": 22, "name": "Limeira", "state": "SP"},
        {"id": 23, "name": "Pirassununga", "state": "SP"},
        {"id": 24, "name": "Jaú", "state": "SP"},
        {"id": 25, "name": "Araraquara", "state": "SP"},
        {"id": 26, "name": "São Carlos", "state": "SP"},
        {"id": 27, "name": "Bauru", "state": "SP"},
        {"id": 28, "name": "Ourinhos", "state": "SP"},
        {"id": 29, "name": "Avaré", "state": "SP"},
        {"id": 30, "name": "Piraju", "state": "SP"},
        {"id": 31, "name": "Marília", "state": "SP"},
        {"id": 32, "name": "Assis", "state": "SP"},
        {"id": 33, "name": "Lins", "state": "SP"},
        {"id": 34, "name": "Franca", "state": "SP"},
        {"id": 35, "name": "Ribeirão Preto", "state": "SP"},
        {"id": 36, "name": "São Joaquim da Barra", "state": "SP"},
        {"id": 37, "name": "São João da Boa Vista", "state": "SP"},
        {"id": 38, "name": "Barretos", "state": "SP"},
        {"id": 39, "name": "Sertãozinho", "state": "SP"},
        {"id": 40, "name": "Jaboticabal", "state": "SP"},
        {"id": 41, "name": "Taquaritinga", "state": "SP"},
        {"id": 42, "name": "Catanduva", "state": "SP"},
        {"id": 43, "name": "São José do Rio Preto", "state": "SP"},
        {"id": 44, "name": "José Bonifácio", "state": "SP"},
        {"id": 45, "name": "Votuporanga", "state": "SP"},
        {"id": 46, "name": "Fernandópolis", "state": "SP"},
        {"id": 47, "name": "Jales", "state": "SP"},
        {"id": 48, "name": "Andradina", "state": "SP"},
        {"id": 49, "name": "Araçatuba", "state": "SP"},
        {"id": 50, "name": "Birigui", "state": "SP"},
        {"id": 51, "name": "Penápolis", "state": "SP"},
        {"id": 52, "name": "Presidente Prudente", "state": "SP"},
        {"id": 53, "name": "Adamantina", "state": "SP"},
        {"id": 54, "name": "Santo Anastácio", "state": "SP"},
        {"id": 55, "name": "Mirante do Paranapanema", "state": "SP"},
        {"id": 56, "name": "Bragança paulista", "state": "SP"},
        {"id": 57, "name": "Piedade", "state": "SP"},
        {"id": 58, "name": "Ibiúna", "state": "SP"},
    ]

def cities_cultures():
    return [
        {"id": 1, "city_id": 1, "culture_id": 1},
        {"id": 2, "city_id": 1, "culture_id": 2},
        {"id": 3, "city_id": 2, "culture_id": 3},
        {"id": 4, "city_id": 3, "culture_id": 3},
        {"id": 5, "city_id": 4, "culture_id": 3},
        {"id": 6, "city_id": 5, "culture_id": 3},
        {"id": 7, "city_id": 6, "culture_id": 3},
        {"id": 8, "city_id": 7, "culture_id": 4},
        {"id": 9, "city_id": 8, "culture_id": 4},
        {"id": 10, "city_id": 9, "culture_id": 4},
        {"id": 11, "city_id": 28, "culture_id": 4},
        {"id": 12, "city_id": 29, "culture_id": 4},
        {"id": 13, "city_id": 30, "culture_id": 4},
        {"id": 14, "city_id": 32, "culture_id": 4},
        {"id": 15, "city_id": 38, "culture_id": 4},
        {"id": 16, "city_id": 52, "culture_id": 4},
        {"id": 17, "city_id": 7, "culture_id": 5},
        {"id": 18, "city_id": 8, "culture_id": 5},
        {"id": 19, "city_id": 9, "culture_id": 5},
        {"id": 20, "city_id": 32, "culture_id": 5},
        {"id": 21, "city_id": 39, "culture_id": 5},
        {"id": 22, "city_id": 40, "culture_id": 5},
        {"id": 23, "city_id": 41, "culture_id": 5},
        {"id": 24, "city_id": 42, "culture_id": 5},
        {"id": 25, "city_id": 43, "culture_id": 5},
        {"id": 26, "city_id": 47, "culture_id": 5},
        {"id": 27, "city_id": 7, "culture_id": 6},
        {"id": 28, "city_id": 8, "culture_id": 6},
        {"id": 29, "city_id": 9, "culture_id": 6},
        {"id": 30, "city_id": 11, "culture_id": 7},
        {"id": 31, "city_id": 12, "culture_id": 7},
        {"id": 32, "city_id": 13, "culture_id": 7},
        {"id": 33, "city_id": 15, "culture_id": 7},
        {"id": 34, "city_id": 16, "culture_id": 7},
        {"id": 35, "city_id": 17, "culture_id": 7},
        {"id": 36, "city_id": 18, "culture_id": 7},
        {"id": 37, "city_id": 19, "culture_id": 7},
        {"id": 38, "city_id": 20, "culture_id": 7},
        {"id": 39, "city_id": 44, "culture_id": 7},
        {"id": 40, "city_id": 45, "culture_id": 7},
        {"id": 41, "city_id": 10, "culture_id": 8},
        {"id": 42, "city_id": 14, "culture_id": 8},
        {"id": 43, "city_id": 20, "culture_id": 8},
        {"id": 44, "city_id": 27, "culture_id": 8},
        {"id": 45, "city_id": 28, "culture_id": 8},
        {"id": 46, "city_id": 29, "culture_id": 8},
        {"id": 47, "city_id": 30, "culture_id": 8},
        {"id": 48, "city_id": 37, "culture_id": 8},
        {"id": 49, "city_id": 38, "culture_id": 8},
        {"id": 50, "city_id": 46, "culture_id": 8},
        {"id": 51, "city_id": 11, "culture_id": 9},
        {"id": 52, "city_id": 12, "culture_id": 9},
        {"id": 53, "city_id": 13, "culture_id": 9},
        {"id": 54, "city_id": 14, "culture_id": 10},
        {"id": 55, "city_id": 20, "culture_id": 10},
        {"id": 56, "city_id": 21, "culture_id": 10},
        {"id": 57, "city_id": 22, "culture_id": 10},
        {"id": 58, "city_id": 23, "culture_id": 10},
        {"id": 59, "city_id": 24, "culture_id": 10},
        {"id": 60, "city_id": 25, "culture_id": 10},
        {"id": 61, "city_id": 26, "culture_id": 10},
        {"id": 62, "city_id": 27, "culture_id": 10},
        {"id": 63, "city_id": 28, "culture_id": 10},
        {"id": 64, "city_id": 29, "culture_id": 10},
        {"id": 65, "city_id": 30, "culture_id": 10},
        {"id": 66, "city_id": 31, "culture_id": 10},
        {"id": 67, "city_id": 32, "culture_id": 10},
        {"id": 68, "city_id": 33, "culture_id": 10},
        {"id": 69, "city_id": 34, "culture_id": 10},
        {"id": 70, "city_id": 35, "culture_id": 10},
        {"id": 71, "city_id": 36, "culture_id": 10},
        {"id": 72, "city_id": 37, "culture_id": 10},
        {"id": 73, "city_id": 38, "culture_id": 10},
        {"id": 74, "city_id": 39, "culture_id": 10},
        {"id": 75, "city_id": 40, "culture_id": 10},
        {"id": 76, "city_id": 41, "culture_id": 10},
        {"id": 77, "city_id": 42, "culture_id": 10},
        {"id": 78, "city_id": 43, "culture_id": 10},
        {"id": 79, "city_id": 44, "culture_id": 10},
        {"id": 80, "city_id": 45, "culture_id": 10},
        {"id": 81, "city_id": 46, "culture_id": 10},
        {"id": 82, "city_id": 47, "culture_id": 10},
        {"id": 83, "city_id": 48, "culture_id": 10},
        {"id": 84, "city_id": 49, "culture_id": 10},
        {"id": 85, "city_id": 50, "culture_id": 10},
        {"id": 86, "city_id": 51, "culture_id": 10},
        {"id": 87, "city_id": 52, "culture_id": 10},
        {"id": 88, "city_id": 53, "culture_id": 10},
        {"id": 89, "city_id": 54, "culture_id": 10},
        {"id": 90, "city_id": 55, "culture_id": 10},
        {"id": 91, "city_id": 15, "culture_id": 11},
        {"id": 92, "city_id": 16, "culture_id": 11},
        {"id": 93, "city_id": 17, "culture_id": 11},
        {"id": 94, "city_id": 18, "culture_id": 11},
        {"id": 95, "city_id": 19, "culture_id": 11},
        {"id": 96, "city_id": 15, "culture_id": 12},
        {"id": 97, "city_id": 16, "culture_id": 12},
        {"id": 98, "city_id": 17, "culture_id": 12},
        {"id": 99, "city_id": 18, "culture_id": 12},
        {"id": 100, "city_id": 19, "culture_id": 12},
        {"id": 101, "city_id": 31, "culture_id": 13},
        {"id": 102, "city_id": 34, "culture_id": 13},
        {"id": 103, "city_id": 37, "culture_id": 13},
        {"id": 104, "city_id": 39, "culture_id": 14},
        {"id": 105, "city_id": 40, "culture_id": 14},
        {"id": 106, "city_id": 41, "culture_id": 14},
        {"id": 107, "city_id": 42, "culture_id": 14},
        {"id": 107, "city_id": 7, "culture_id": 15},
        {"id": 107, "city_id": 11, "culture_id": 15},
        {"id": 107, "city_id": 56, "culture_id": 15},
        {"id": 107, "city_id": 42, "culture_id": 16},
        {"id": 107, "city_id": 47, "culture_id": 16},
        {"id": 107, "city_id": 38, "culture_id": 16},
        {"id": 107, "city_id": 14, "culture_id": 16},
        {"id": 107, "city_id": 40, "culture_id": 16},
        {"id": 107, "city_id": 7, "culture_id": 17},
        {"id": 107, "city_id": 38, "culture_id": 17},
        {"id": 107, "city_id": 9, "culture_id": 17},
        {"id": 107, "city_id": 2, "culture_id": 18},
        {"id": 107, "city_id": 19, "culture_id": 18},
        {"id": 107, "city_id": 11, "culture_id": 18},
        {"id": 107, "city_id": 57, "culture_id": 19},
        {"id": 107, "city_id": 58, "culture_id": 19},
        {"id": 107, "city_id": 35, "culture_id": 20},
        {"id": 107, "city_id": 40, "culture_id": 20},
    ]